### ISSUE TITLE
Shows as disabled in the Plugins

### ISSUE THREAD

**Issue by SlightOmission** [MonDiscourse/discourse-formatting-toolbar#4]
I've installed v3.1 of the plugin but under the enabled column it shows "N".  I don't see where to enable it though.  The "Activate the formatting toolbar?" option in the settings is checked.

<img width="1166" alt="screen shot 2018-04-20 at 6 47 40 pm" src="https://user-images.githubusercontent.com/2685312/39079238-57f79544-44cb-11e8-8b41-46147f96a406.png">

**Comment by ghost** [comment]
Thanks for installing the plugin. This is a weird behavior, I'll run some
tests tomorrow, I don't have this issue bit it may be related to latest
discourses updates

Le sam. 21 avr. 2018 à 03:49, Landon Stewart <notifications@github.com> a
écrit :

**Comment by ghost** [comment]
I checked on a test forum. I have the same issue. Do you still have the new buttons on the toolbar ?

![image](https://user-images.githubusercontent.com/12373169/39088728-7a2694d4-45b7-11e8-8d52-c4ac829d22ae.png)

**Comment by SlightOmission** [comment]
Thanks for checking on this.  I don't think the toolbar has changed.  These are the buttons I see in the editor toolbar:

<img width="733" alt="screen shot 2018-04-21 at 2 20 51 pm" src="https://user-images.githubusercontent.com/2685312/39088884-3b5b4008-456f-11e8-8e65-2cef5b2d9145.png">

**Comment by ghost** [comment]
Ok at least it works. 

It may be related to the last update with the size button that is not activated by default, I don't think I did something wrong there, I'll verify the code

**Comment by hhyyrylainen** [comment]
I think I just got the same issue after updating discourse a couple of days ago, with a rebuild to add the new key for IP database download.

Update: doing a rebuild of discourse fixed the issue for me.
