### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by ylluminate** [MonDiscourse/discourse-formatting-toolbar#5]
Could you give us several example sites that are using this that we might sign up on to see this plugin in action? It seems the main site is in French and so it might be easier for many users to have at least an English language example.

**Comment by ghost** [comment]
I installed it on french sites only, and I didn't have a lot of feedback.

But it seems that Jordan Dayton use the plugin on his forum : https://community.jewelbound.com/
You can also sign up on a forum like http://handballtransfert.com/ (mostly french) and switch to english language after
Same on my forum : https://iunctis.fr/
